"""Thread-safe, in-memory operator sessions for the local control plane."""

from __future__ import annotations

import hashlib
import hmac
import math
import secrets
import string
import threading
import time
from types import MappingProxyType
from typing import Any, Mapping


ROLE_PERMISSIONS: Mapping[str, frozenset[str]] = MappingProxyType(
    {
        "admin": frozenset(
            {"read", "task_write", "note_write", "reset", "operator_admin"}
        ),
        "operator": frozenset({"read", "task_write", "note_write"}),
        "viewer": frozenset({"read"}),
    }
)
ROLES = frozenset(ROLE_PERMISSIONS)
PERMISSIONS = frozenset(
    permission for permissions in ROLE_PERMISSIONS.values() for permission in permissions
)

DEFAULT_SESSION_TTL_SECONDS = 8 * 60 * 60
MAX_SESSION_TTL_SECONDS = 30 * 24 * 60 * 60
MAX_OPERATOR_SESSIONS = 64
MIN_TOKEN_LENGTH = 24
MAX_TOKEN_LENGTH = 512
MIN_PRINCIPAL_ID_LENGTH = 3
MAX_PRINCIPAL_ID_LENGTH = 48

_PRINCIPAL_FIRST_CHARACTERS = frozenset(string.ascii_lowercase)
_PRINCIPAL_BODY_CHARACTERS = frozenset(string.ascii_lowercase + string.digits + "_-")
_PRINCIPAL_SEPARATORS = frozenset("_-")
_HEX_CHARACTERS = frozenset(string.hexdigits.lower())


class AuthError(ValueError):
    """An operator-session validation or authorization failure safe for the API."""

    def __init__(self, message: str, *, code: str = "invalid_request", status: int = 400):
        super().__init__(message)
        self.message = message
        self.code = code
        self.status = status


def _validate_principal_id(value: Any) -> str:
    if (
        not isinstance(value, str)
        or not MIN_PRINCIPAL_ID_LENGTH <= len(value) <= MAX_PRINCIPAL_ID_LENGTH
        or value[0] not in _PRINCIPAL_FIRST_CHARACTERS
        or value[-1] in _PRINCIPAL_SEPARATORS
        or any(character not in _PRINCIPAL_BODY_CHARACTERS for character in value)
        or any(
            current in _PRINCIPAL_SEPARATORS and following in _PRINCIPAL_SEPARATORS
            for current, following in zip(value, value[1:])
        )
    ):
        raise AuthError(
            "principal_id must be a canonical lowercase identifier containing "
            f"{MIN_PRINCIPAL_ID_LENGTH} to {MAX_PRINCIPAL_ID_LENGTH} characters"
        )
    return value


def _validate_role(value: Any) -> str:
    if not isinstance(value, str) or value not in ROLE_PERMISSIONS:
        raise AuthError("role must be admin, operator, or viewer")
    return value


def _token_is_valid(value: Any) -> bool:
    return (
        isinstance(value, str)
        and MIN_TOKEN_LENGTH <= len(value) <= MAX_TOKEN_LENGTH
        and value.isascii()
        and all(33 <= ord(character) <= 126 for character in value)
    )


def _validate_token(value: Any) -> str:
    if not _token_is_valid(value):
        raise AuthError(
            "token must be a printable ASCII secret containing "
            f"{MIN_TOKEN_LENGTH} to {MAX_TOKEN_LENGTH} characters"
        )
    return value


def _validate_session_id(value: Any, field: str = "session_id") -> str:
    prefix = "op-session-"
    if (
        not isinstance(value, str)
        or not value.startswith(prefix)
        or len(value) != len(prefix) + 24
        or any(character not in _HEX_CHARACTERS for character in value[len(prefix) :])
    ):
        raise AuthError(f"{field} is invalid")
    return value


def _validate_ttl(value: Any) -> float:
    if (
        not isinstance(value, (int, float))
        or isinstance(value, bool)
        or not math.isfinite(value)
        or not 0 < value <= MAX_SESSION_TTL_SECONDS
    ):
        raise AuthError(
            f"ttl_seconds must be greater than zero and at most {MAX_SESSION_TTL_SECONDS}"
        )
    return float(value)


def _resolve_now(value: float | None) -> float:
    instant: Any = time.monotonic() if value is None else value
    if (
        not isinstance(instant, (int, float))
        or isinstance(instant, bool)
        or not math.isfinite(instant)
        or instant < 0
    ):
        raise AuthError("now must be a non-negative finite monotonic timestamp")
    return float(instant)


def _token_digest(token: str) -> bytes:
    return hashlib.sha256(token.encode("ascii")).digest()


class OperatorSessionRegistry:
    """Memory-only operator sessions with fixed role permissions.

    Tokens must be generated by the caller. Only a one-way digest is retained,
    and every returned session is a token-free public representation.
    """

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._sessions: dict[str, dict[str, Any]] = {}

    def register(
        self,
        principal_id: Any,
        role: Any,
        token: Any,
        *,
        ttl_seconds: Any = DEFAULT_SESSION_TTL_SECONDS,
        now: float | None = None,
    ) -> dict[str, Any]:
        """Register a caller-generated token and return its public session."""

        clean_principal_id = _validate_principal_id(principal_id)
        clean_role = _validate_role(role)
        clean_token = _validate_token(token)
        clean_ttl = _validate_ttl(ttl_seconds)
        instant = _resolve_now(now)
        digest = _token_digest(clean_token)

        with self._lock:
            if any(
                hmac.compare_digest(digest, session["_token_digest"])
                for session in self._sessions.values()
            ):
                raise AuthError("token is already registered", code="token_conflict", status=409)
            if len(self._sessions) >= MAX_OPERATOR_SESSIONS:
                inactive_id = next(
                    (
                        session_id
                        for session_id, session in self._sessions.items()
                        if not self._is_active_locked(session, instant)
                    ),
                    None,
                )
                if inactive_id is None:
                    raise AuthError(
                        "operator session limit reached",
                        code="session_limit",
                        status=429,
                    )
                del self._sessions[inactive_id]

            session_id = self._new_session_id_locked()
            session = {
                "id": session_id,
                "principal_id": clean_principal_id,
                "role": clean_role,
                "_token_digest": digest,
                "_created_monotonic": instant,
                "_expires_monotonic": instant + clean_ttl,
                "_revoked_monotonic": None,
            }
            self._sessions[session_id] = session
            return self._public_locked(session, instant)

    def authenticate(
        self,
        token: Any,
        *,
        permission: str | None = None,
        now: float | None = None,
    ) -> dict[str, Any] | None:
        """Return an active public session authorized for ``permission``."""

        if permission is not None and permission not in PERMISSIONS:
            raise AuthError("permission is not recognized", code="invalid_permission")
        if not _token_is_valid(token):
            return None
        instant = _resolve_now(now)
        digest = _token_digest(token)

        with self._lock:
            matched: dict[str, Any] | None = None
            for session in self._sessions.values():
                if hmac.compare_digest(digest, session["_token_digest"]):
                    matched = session
            if matched is None or not self._is_active_locked(matched, instant):
                return None
            if permission is not None and permission not in ROLE_PERMISSIONS[matched["role"]]:
                return None
            return self._public_locked(matched, instant)

    def revoke(
        self,
        session_id: Any,
        *,
        actor_session_id: Any | None = None,
        now: float | None = None,
    ) -> dict[str, Any]:
        """Revoke a session.

        Omitting ``actor_session_id`` means a self-revocation. Revoking another
        session requires an active session with ``operator_admin`` permission.
        The sole active admin session cannot revoke itself.
        """

        clean_session_id = _validate_session_id(session_id)
        clean_actor_session_id = (
            clean_session_id
            if actor_session_id is None
            else _validate_session_id(actor_session_id, "actor_session_id")
        )
        instant = _resolve_now(now)

        with self._lock:
            target = self._sessions.get(clean_session_id)
            if target is None:
                raise AuthError("session was not found", code="session_not_found", status=404)
            if (
                target["_revoked_monotonic"] is not None
                and clean_actor_session_id == clean_session_id
            ):
                return self._public_locked(target, instant)

            actor = self._sessions.get(clean_actor_session_id)
            if actor is None or not self._is_active_locked(actor, instant):
                raise AuthError("an active actor session is required", code="unauthorized", status=401)
            if (
                clean_actor_session_id != clean_session_id
                and "operator_admin" not in ROLE_PERMISSIONS[actor["role"]]
            ):
                raise AuthError(
                    "operator_admin permission is required",
                    code="forbidden",
                    status=403,
                )
            if target["_revoked_monotonic"] is not None:
                return self._public_locked(target, instant)

            if clean_actor_session_id == clean_session_id and target["role"] == "admin":
                active_admins = sum(
                    session["role"] == "admin" and self._is_active_locked(session, instant)
                    for session in self._sessions.values()
                )
                if active_admins <= 1:
                    raise AuthError(
                        "the last active admin session cannot revoke itself",
                        code="last_admin_session",
                        status=409,
                    )

            target["_revoked_monotonic"] = instant
            return self._public_locked(target, instant)

    def list(self, *, now: float | None = None) -> list[dict[str, Any]]:
        """List token-free public sessions, including expired and revoked ones."""

        instant = _resolve_now(now)
        with self._lock:
            return [self._public_locked(session, instant) for session in self._sessions.values()]

    def register_session(
        self,
        principal_id: Any,
        role: Any,
        token: Any,
        *,
        ttl_seconds: Any = DEFAULT_SESSION_TTL_SECONDS,
        now: float | None = None,
    ) -> dict[str, Any]:
        """Explicitly named alias for :meth:`register`."""

        return self.register(
            principal_id,
            role,
            token,
            ttl_seconds=ttl_seconds,
            now=now,
        )

    def list_sessions(self, *, now: float | None = None) -> list[dict[str, Any]]:
        """Explicitly named alias for :meth:`list`."""

        return self.list(now=now)

    def _new_session_id_locked(self) -> str:
        while True:
            candidate = f"op-session-{secrets.token_hex(12)}"
            if candidate not in self._sessions:
                return candidate

    @staticmethod
    def _is_active_locked(session: dict[str, Any], now: float) -> bool:
        return session["_revoked_monotonic"] is None and now < session["_expires_monotonic"]

    def _public_locked(self, session: dict[str, Any], now: float) -> dict[str, Any]:
        revoked_at = session["_revoked_monotonic"]
        if revoked_at is not None:
            status = "revoked"
        elif now >= session["_expires_monotonic"]:
            status = "expired"
        else:
            status = "active"
        return {
            "id": session["id"],
            "principal_id": session["principal_id"],
            "role": session["role"],
            "permissions": sorted(ROLE_PERMISSIONS[session["role"]]),
            "created_monotonic": session["_created_monotonic"],
            "expires_monotonic": session["_expires_monotonic"],
            "expires_in_seconds": round(
                max(0.0, session["_expires_monotonic"] - now),
                3,
            ),
            "revoked_monotonic": revoked_at,
            "status": status,
            "active": status == "active",
        }
